source 'https://rubygems.org'
ruby '1.9.3'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'haml'
gem 'warden'
gem 'pony'
gem 'sinatra-subdomain'
gem 'nokogiri'
gem 'carrierwave'
gem 'carrierwave-datamapper'
gem 'mini_magick'