source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'haml'
gem 'warden'
gem 'pony'
gem 'sinatra-subdomain'
gem 'nokogiri'
gem 'carrierwave'
gem 'carrierwave-datamapper'
gem 'mini_magick'
gem 'thin'
gem 'unicode'
gem 'keepass-password-generator'
gem 'will_paginate'